More complex template for makefile with libraries

diff --git a/Examples/Makefile_template_lib b/Examples/Makefile_template_lib
--- a/Examples/Makefile_template_lib
+++ b/Examples/Makefile_template_lib
@@ -15,7 +15,34 @@
 
 MAKEFILEH_DIR=../../
 #
+LIBNAME=fpe
+DYNAMIC_LIBFILE=lib$(LIBNAME).so
+STATIC_LIBFILE=lib$(LIBNAME).a
+
 include $(MAKEFILEH_DIR)/Makefile.inc
+LIBRARIES+=-L. -l$(LIBNAME)
+
+ifeq ($(LIBTYPE),DYNAMIC)
+ EXTRA_CXXFLAGS=-fPIC
+ export LIBRARY=$(DYNAMIC_LIBFILE)
+ LDFLAGS+=-dynamic 
+else
+ EXTRA_CXXFLAGS=
+ export LIBRARY=$(STATIC_LIBFILE)
+ LDFLAGS+=-static
+endif
+export DEBUG
+ifeq ($(DEBUG),yes)
+  OPTFLAGS=-g -O0
+  LDFLAGS+=-Wl,-rpath=.
+else
+  OPTFLAGS=-O3
+endif
+ifeq ($(FPEABORT),yes)
+ EXEC_CPPFLAGS=-DFPE_ABORT
+else
+ EXEC_CPPFLAGS=
+endif
 #
 # You may have an include file also in the current directory
 #
@@ -32,50 +59,82 @@ SRCS=$(wildcard *.cpp)
 # get the corresponding object file
 OBJS = $(SRCS:.cpp=.o)
 # object file for a library if needed
-LIB_OBJS:=$(filter-out main%.o,$(OBJS))
+LIB_SRCS:=myexceptions.cpp trapfpe.cpp
+LIB_OBJS:=$(LIB_SRCS:.cpp=.o)
+LIB_HEADERS:=$(LIB_SRCS:.cpp=.hpp)
+OTHER_OBJS:=rational.o
+OTHER_SRCS:=rational.cpp
 # get all headers in the working directory
 HEADERS=$(wildcard *.hpp)
 #
 exe_sources=$(filter main%.cpp,$(SRCS))
 EXEC=$(exe_sources:.cpp=)
-
+EXEC_OBJS=$(exe_sources:.cpp=.o)
+EXEC_SRCS:=$(exe_sources)
 #========================== ORA LA DEFINIZIONE DEGLI OBIETTIVI
-.phony= all clean distclean doc
+.phony= all clean distclean doc static dynamic depend install
 
 .DEFAULT_GOAL = all
 
-all: $(DEPEND) $(EXEC)
+all:
+	@echo "make static makes static library and executable"
+	@echo "make dynamic makes dynamic library and executable"
+	@echo "make depend just makes dependency file"
+	@echo "make clean cleans all not library"
+	@echo "make distclean cleans all"
+	@echo "make install installs"
+	@echo "macro DEBUG=yes  activates debugging"
+	@echo "macro FPEABORT=yes  activates abort on FPE"
 
-library:$(STATIC_LIBFILE) $(DYNAMIC_LIBFILE)
+depend: $(DEPEND)
+
+static:
+	-rm $(LIB_OBJS)
+	$(MAKE) library LIBTYPE=STATIC 
+	$(MAKE) exec LIBTYPE=STATIC 
+dynamic:
+	-rm $(LIB_OBJS)
+	$(MAKE) library LIBTYPE=DYNAMIC
+	$(MAKE) exec LIBTYPE=DYNAMIC
+
+exec: $(EXEC)
+
+library:  $(LIBRARY)
 
 install:
-	cp ./include/*.hpp $(PACS_INC_DIR)
+	cp $(LIB_HEADERS) $(PACS_INC_DIR)
 	cp $(STATIC_LIBFILE) $(DYNAMIC_LIBFILE) $(PACS_LIB_DIR)
 clean:
 	-\rm -f $(EXEC) $(OBJS)
 
 distclean:
 	$(MAKE) clean
-	-\rm -r -f ./doc
+	-\rm -r -f ./doc $(STATIC_LIBFILE) $(DYNAMIC_LIBFILE)
 	-\rm *.out *.bak *~
 
 doc:
 	doxygen $(DOXYFILE)
 
-$(EXEC): $(OBJS)
+$(EXEC): $(EXEC_OBJS) $(OTHER_OBJS)
+	$(CXX) $(EXEC_OBJS) $(OTHER_OBJS) $(LDFLAGS) -o $(EXEC)
 
-$(OBJS): $(SRCS)
+$(EXEC_OBJS): $(EXEC_SRCS)
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(EXEC_CPPFLAGS) -c $?
+
+$(OTHER_OBJS): $(OTHER_SRCS)
+	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $?
 
 $(STATIC_LIBFILE): $(STATIC_LIBFILE)($(LIB_OBJS))
 	ar -r $(STATIC_LIBFILE) $(LIB_OBJS)
 
-$(DYNAMIC_LIBFILE):
-	make clean
-	$(MAKE) CXXFLAGS=-fPIC $(LIB_OBJS)
-	$(CXX) -shared $(LIB_OBJS) -o $(DYNAMIC_LIBFILE)
+$(DYNAMIC_LIBFILE): $(LIB_OBJS)
+	$(CXX) -shared $(OPTFLAGS) $(LIBD) $(LIB_OBJS) -o $(DYNAMIC_LIBFILE)
+
+$(LIB_OBJS): $(LIB_SRCS)
+	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -fPIC -c $?
 
 $(DEPEND): $(SRCS) $(HEADERS)
-	g++ $(CPPFLAGS) -MM $(SRCS) -MF $(DEPEND)
+	g++ -std=c++0x $(CPPFLAGS) -MM $(SRCS) -MF $(DEPEND)
 
 
 
